<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net46;net6.0-windows10.0.19041.0</TargetFrameworks>
    <Version>0.0.6-clean</Version>
    <LangVersion>10.0</LangVersion>
    <RootNamespace>WindowsDesktop</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <PackageId>LostTech.VirtualDesktop</PackageId>
    <Authors>grabacr.net, Victor Milovanov</Authors>
    <Company>Lost Tech LLC, grabacr.net</Company>
    <Description>C# wrapper for IVirtualDesktopManager on Windows 10. You need to include the app manifest in your project so as to target Windows 10.</Description>
    <Copyright>© 2022 Lost Tech LLC; © 2015 Manato KAMEYA</Copyright>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageProjectUrl>https://github.com/losttech/VirtualDesktop</PackageProjectUrl>
    <RepositoryUrl>https://github.com/losttech/VirtualDesktop.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>Windows Windows10 Desktop VirtualDesktop</PackageTags>
    <PackageReleaseNotes>All customized APIs are declared deprecated</PackageReleaseNotes>

    <!-- The following is recommended for public projects -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <DebugSymbols>true</DebugSymbols>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <!-- The following is recommended for public projects -->
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All" />
  </ItemGroup>

</Project>
